# Generated by Django 4.0.6 on 2022-07-22 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='myprd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=30)),
                ('pcat', models.CharField(max_length=50)),
                ('psubcat', models.CharField(max_length=60)),
                ('pdes', models.CharField(max_length=120)),
                ('pdate', models.DateField()),
                ('pimg', models.ImageField(upload_to='shop/images')),
                ('pcost', models.IntegerField()),
            ],
        ),
    ]
