# Generated by Django 4.0.6 on 2022-07-31 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0002_prdlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('mail', models.CharField(max_length=60)),
                ('phone', models.IntegerField()),
                ('message', models.CharField(max_length=600)),
            ],
        ),
    ]
