# Generated by Django 4.0.6 on 2022-08-04 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items', models.CharField(max_length=8000)),
                ('name', models.CharField(max_length=40)),
                ('phone', models.IntegerField()),
                ('email', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=80)),
                ('state', models.CharField(max_length=120)),
                ('pin', models.IntegerField()),
            ],
        ),
    ]
