# Generated by Django 4.0.6 on 2022-08-04 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0005_rename_address_order_address1_order_address2'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderstatus',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField()),
                ('status', models.CharField(max_length=500)),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
